image: "alpine:3.17.5"
variables:
  JEKYLL_ENV: "production"
  LC_ALL: "C.UTF-8"
test:
  stage: "test"
  before_script:
  - "apk add libffi libstdc++ libxslt libxml2 tzdata ruby ruby-bundler ruby-json ruby-bigdecimal ruby-rake vips libmagic yarn"
  - "bundle install --deployment --without test development"
  - "yarn install --production"
  script:
  - "bundle exec jekyll build"
