image: "alpine:3.14.10"
variables:
  JEKYLL_ENV: "production"
  LC_ALL: "C.UTF-8"
test:
  stage: "test"
  before_script:
  - "apk add libffi libstdc++ libxslt libxml2 tzdata ruby ruby-bundler ruby-json ruby-bigdecimal ruby-rake vips libmagic"
  - "bundle install --deployment --without test development"
  script:
  - "bundle exec jekyll build"
