---
incremental: false
early_plugins:
- gem: jekyll-activity-pub
  require: jekyll/activity_pub/commands
plugins:
- jekyll-activity-pub
- jekyll-brotli
- jekyll-commonmark
- jekyll-data
- jekyll-drafts-as-metadata
- jekyll-embed-urls
- jekyll-env
- jekyll-feed
- jekyll-gzip
- jekyll-hardlinks
- jekyll-ignore-layouts
- jekyll-include-cache
- jekyll-images
- jekyll-linked-posts
- jekyll-locales
- jekyll-onion-location
- jekyll-order
- jekyll-purgecss
- jekyll-relative-urls
- jekyll-unique-urls
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-write-and-commit-changes
- sutty-liquid
sass:
  style: compressed
  load_paths:
  - node_modules
liquid:
  yaml_to_scss:
    reject_keys:
    - uuid
    - locales
    - title
    - order
    - draft
exclude:
- Dockerfile
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- pnpm-lock.yaml
- purgecss.config.js
- README.md
- yarn.lock
markdown: CommonMark
commonmark:
  options:
  - SMART
  - FOOTNOTES
  - UNSAFE
  extensions:
  - strikethrough
  - autolink
  - table
locales:
- es
- en
theme: sutty-minima
ignored_layouts:
- menu
- about
- theme
css_dir: assets/css
linked_fields:
- locales
brotli:
  quality: 9
defaults:
- scope:
    type: posts
  values:
    activity: false
activity_pub:
  url: https://social.dp.chanterelle.xyz
