---
incremental: false
plugins:
- sutty-liquid
- jekyll-locales
- jekyll-order
- jekyll-data
- jekyll-drafts-as-metadata
- jekyll-embed-urls
- jekyll-relative-urls
- jekyll-commonmark
- jekyll-onion-location
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-turbolinks
- jekyll-include-cache
- jekyll-purgecss
- jekyll-brotli
- jekyll-gzip
sass:
  style: compressed
  load_paths:
  - node_modules
exclude:
- package.json
- yarn.lock
- node_modules
- Dockerfile
- Gemfile
- Gemfile.lock
markdown: CommonMark
commonmark:
  options:
  - SMART
  - FOOTNOTES
  - UNSAFE
  extensions:
  - strikethrough
  - autolink
  - table
locales:
- es
- en
theme: sutty-jekyll-theme
turbolinks:
  enabled: true
  url: turbolinks.js
